version: "3.7"
services:
  app:
    build:
      args:
        user: ${USER_NAME}
        uid: ${USER_UID}
      context: ./docker/app/
      dockerfile: Dockerfile
    image: php-image
    container_name: ${PROJECT_NAME}-app
    restart: unless-stopped
    working_dir: /var/www/
    environment:
      XDEBUG_CONFIG: "client_host=host.docker.internal client_port=9003 remote_enable=1"
      PHP_IDE_CONFIG: "serverName=Docker"
    volumes:
      - ./docker/app/php.ini:/usr/local/etc/php/php.ini
      - ./:/var/www
    networks:
      - docker-net
  db:
    image: mysql:5.7
    platform: linux/x86_64
    container_name: ${PROJECT_NAME}-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
      - 3306:3306
    volumes:
      - ./db/:/var/lib/mysql
    networks:
      - docker-net
  nginx:
    image: nginx:alpine
    container_name: ${PROJECT_NAME}-nginx
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d/
    networks:
      - docker-net
  nodejs:
    build:
      context: ./docker/nodejs/
      dockerfile: Dockerfile
    platform: linux/x86_64
    container_name: ${PROJECT_NAME}-node
    restart: unless-stopped
    volumes:
      - ./:/home/node/app
    networks:
      - docker-net

networks:
  docker-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.220.0/28
